### ISSUE TITLE
IPv6 interface {} is nil, not string

### ISSUE THREAD

**Issue by securebitag** [alice-lg/birdwatcher#46]
Jan 28 16:52:05 rs1 birdwatcher[485554]: panic: interface conversion: interface {} is nil, not string 
Jan 28 16:52:05 rs1 birdwatcher[485554]: goroutine 33 [running]: 
Jan 28 16:52:05 rs1 birdwatcher[485554]: github.com/alice-lg/birdwatcher/bird.parseRouteLines(0xc000126400, 0x12, 0x20, 0x75, 0xc000060180) 
Jan 28 16:52:05 rs1 birdwatcher[485554]: #011/root/go/pkg/mod/github.com/alice-lg/birdwatcher@v0.0.0-20220607085947-7f1eb5a0e458/bird/parser.go:335 +0x1089 
Jan 28 16:52:05 rs1 birdwatcher[485554]: github.com/alice-lg/birdwatcher/bird.workerForRouteBlockParsing(0xc000060120, 0xc000060180, 0xc0002a60c0) 
Jan 28 16:52:05 rs1 birdwatcher[485554]: #011/root/go/pkg/mod/github.com/alice-lg/birdwatcher@v0.0.0-20220607085947-7f1eb5a0e458/bird/parser.go:313 +0x73 
Jan 28 16:52:05 rs1 birdwatcher[485554]: created by github.com/alice-lg/birdwatcher/bird.startRouteWorkers.func1 
Jan 28 16:52:05 rs1 birdwatcher[485554]: #011/root/go/pkg/mod/github.com/alice-lg/birdwatcher@v0.0.0-20220607085947-7f1eb5a0e458/bird/parser.go:271 +0x65 
Jan 28 16:52:05 rs1 systemd[1]: birdwatcher6.service: Main process exited, code=exited, status=2/INVALIDARGUMENT 
Jan 28 16:52:05 rs1 systemd[1]: birdwatcher6.service: Failed with result 'exit-code'.

**Comment by annikahannig** [comment]
I think I need some more details on the birdc output
Can you please attach the output of `birdc show route all`?

(Or `show route table 'master6' all` depending on your setup).

**Comment by annikahannig** [comment]
Looks like `parseMainRouteDetail[Bird2]` does not fill in the `network` attribute, so I would need to see the output and check why the regex fails.

**Comment by securebitag** [comment]
Thanks for your fast feedback.

There are a lot of routes, to much to paste here.
I posted them on pastebin:
https://pastebin.com/QxbHLr8Q

**Comment by annikahannig** [comment]
Thanks. I could not see anything obviously wrong and tried some of the regexes in use.
I'll need to make a test case out of this and investigate deeper.

**Comment by securebitag** [comment]
ok, thank you.
if we can help in this case, please let us know.
