### ISSUE TITLE
Killed

### ISSUE THREAD

**Issue by maximiliandallmair** [alice-lg/birdwatcher#9]
```
Housekeeping started
Expiring MemoryCache
Expired 0 entries (MemoryCache)
Freeing memory
192.168.1.70 - - [23/Jul/2019:07:11:55 +0000] "GET /protocols HTTP/1.1" 200 819
192.168.1.70 - - [23/Jul/2019:07:12:02 +0000] "GET /protocols HTTP/1.1" 200 818
192.168.1.70 - - [23/Jul/2019:07:12:02 +0000] "GET /status HTTP/1.1" 200 317
192.168.1.70 - - [23/Jul/2019:07:12:10 +0000] "GET /protocols HTTP/1.1" 200 818
192.168.1.70 - - [23/Jul/2019:07:12:02 +0000] "GET /routes/peer/192.168.1.251 HTTP/1.1" 200 19704766
192.168.1.70 - - [23/Jul/2019:07:12:37 +0000] "GET /protocols HTTP/1.1" 200 818
192.168.1.70 - - [23/Jul/2019:07:12:37 +0000] "GET /routes/filtered/AS65535 HTTP/1.1" 200 172
192.168.1.70 - - [23/Jul/2019:07:12:40 +0000] "GET /protocols HTTP/1.1" 200 818
192.168.1.70 - - [23/Jul/2019:07:12:40 +0000] "GET /routes/peer/192.168.1.251 HTTP/1.1" 500 28
Killed
```
possible because view of full table?

**Comment by maximiliandallmair** [comment]
Sometimtes:
```Housekeeping started
Expiring MemoryCache
Expired 0 entries (MemoryCache)
Freeing memory
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x7fc571, 0x16)
        /usr/lib/go-1.11/src/runtime/panic.go:608 +0x72
runtime.sysMap(0xc1d8000000, 0x4000000, 0xb223f8)
        /usr/lib/go-1.11/src/runtime/mem_linux.go:156 +0xc7
runtime.(*mheap).sysAlloc(0xb09120, 0x4000000, 0x7fcabdd2ff70, 0x7fcadbffecd8)
        /usr/lib/go-1.11/src/runtime/malloc.go:619 +0x1c7
runtime.(*mheap).grow(0xb09120, 0x8fa, 0x0)
        /usr/lib/go-1.11/src/runtime/mheap.go:920 +0x42
runtime.(*mheap).allocSpanLocked(0xb09120, 0x8fa, 0xb22408, 0xc13a70c000)
        /usr/lib/go-1.11/src/runtime/mheap.go:848 +0x337
runtime.(*mheap).alloc_m(0xb09120, 0x8fa, 0xb00101, 0xc13eaa3000)
        /usr/lib/go-1.11/src/runtime/mheap.go:692 +0x119
runtime.(*mheap).alloc.func1()
        /usr/lib/go-1.11/src/runtime/mheap.go:759 +0x4c
runtime.(*mheap).alloc(0xb09120, 0x8fa, 0x7fcabb010101, 0x53)
        /usr/lib/go-1.11/src/runtime/mheap.go:758 +0x8a
runtime.largeAlloc(0x11f3177, 0x7fcadbff0101, 0x454dea)
        /usr/lib/go-1.11/src/runtime/malloc.go:1019 +0x97
runtime.mallocgc.func1()
        /usr/lib/go-1.11/src/runtime/malloc.go:914 +0x46
runtime.systemstack(0xc0001b8000)
        /usr/lib/go-1.11/src/runtime/asm_amd64.s:351 +0x66
runtime.mstart()
        /usr/lib/go-1.11/src/runtime/proc.go:1229

goroutine 22 [running]:
runtime.systemstack_switch()
        /usr/lib/go-1.11/src/runtime/asm_amd64.s:311 fp=0xc0000caeb0 sp=0xc0000caea8 pc=0x456760
runtime.mallocgc(0x11f3177, 0x76c820, 0x1, 0xc0000caf88)
        /usr/lib/go-1.11/src/runtime/malloc.go:913 +0x896 fp=0xc0000caf50 sp=0xc0000caeb0 pc=0x40d556
runtime.makeslice(0x76c820, 0x11f3177, 0x11f3177, 0x0, 0x7fcab3b45600, 0x4)
        /usr/lib/go-1.11/src/runtime/slice.go:70 +0x77 fp=0xc0000caf80 sp=0xc0000caf50 pc=0x441c37
bytes.makeSlice(0x11f3177, 0x0, 0x0, 0x0)
        /usr/lib/go-1.11/src/bytes/buffer.go:231 +0x6d fp=0xc0000cafc0 sp=0xc0000caf80 pc=0x4d538d
bytes.(*Buffer).grow(0xc1d144c8f0, 0x1, 0x4bbc7f)
        /usr/lib/go-1.11/src/bytes/buffer.go:144 +0x16c fp=0xc0000cb010 sp=0xc0000cafc0 pc=0x4d4cec
bytes.(*Buffer).WriteByte(0xc1d144c8f0, 0x22, 0x6, 0x97)
        /usr/lib/go-1.11/src/bytes/buffer.go:269 +0x91 fp=0xc0000cb038 sp=0xc0000cb010 pc=0x4d55e1
encoding/json.(*encodeState).string(0xc1d144c8f0, 0x7f6ede, 0x7, 0xc139c65501)
        /usr/lib/go-1.11/src/encoding/json/encode.go:885 +0x36 fp=0xc0000cb098 sp=0xc0000cb038 pc=0x674256
encoding/json.(*mapEncoder).encode(0xc00000e180, 0xc1d144c8f0, 0x788280, 0xc0081b0d20, 0x15, 0x780100)
        /usr/lib/go-1.11/src/encoding/json/encode.go:690 +0x2c1 fp=0xc0000cb208 sp=0xc0000cb098 pc=0x672691
encoding/json.(*mapEncoder).encode-fm(0xc1d144c8f0, 0x788280, 0xc0081b0d20, 0x15, 0xc0081b0100)
        /usr/lib/go-1.11/src/encoding/json/encode.go:708 +0x64 fp=0xc0000cb248 sp=0xc0000cb208 pc=0x67a8c4
encoding/json.(*encodeState).reflectValue(0xc1d144c8f0, 0x788280, 0xc0081b0d20, 0x15, 0xc0081b0100)
        /usr/lib/go-1.11/src/encoding/json/encode.go:333 +0x82 fp=0xc0000cb280 sp=0xc0000cb248 pc=0x66f992
encoding/json.interfaceEncoder(0xc1d144c8f0, 0x77e600, 0xc156cf2390, 0x94, 0xc156cf0100)
        /usr/lib/go-1.11/src/encoding/json/encode.go:619 +0xab fp=0xc0000cb2c8 sp=0xc0000cb280 pc=0x671beb
encoding/json.(*mapEncoder).encode(0xc00000e180, 0xc1d144c8f0, 0x788280, 0xc1d5ea7aa8, 0x195, 0x100)
        /usr/lib/go-1.11/src/encoding/json/encode.go:692 +0x37b fp=0xc0000cb438 sp=0xc0000cb2c8 pc=0x67274b
encoding/json.(*mapEncoder).encode-fm(0xc1d144c8f0, 0x788280, 0xc1d5ea7aa8, 0x195, 0x780100)
        /usr/lib/go-1.11/src/encoding/json/encode.go:708 +0x64 fp=0xc0000cb478 sp=0xc0000cb438 pc=0x67a8c4
encoding/json.(*arrayEncoder).encode(0xc09be23448, 0xc1d144c8f0, 0x766a60, 0xc13f5d2000, 0x97, 0x660100)
        /usr/lib/go-1.11/src/encoding/json/encode.go:769 +0xdc fp=0xc0000cb4d0 sp=0xc0000cb478 pc=0x67345c
encoding/json.(*arrayEncoder).encode-fm(0xc1d144c8f0, 0x766a60, 0xc13f5d2000, 0x97, 0x410100)
        /usr/lib/go-1.11/src/encoding/json/encode.go:776 +0x64 fp=0xc0000cb510 sp=0xc0000cb4d0 pc=0x67a9c4
encoding/json.(*sliceEncoder).encode(0xc09be23450, 0xc1d144c8f0, 0x766a60, 0xc13f5d2000, 0x97, 0x760100)
        /usr/lib/go-1.11/src/encoding/json/encode.go:743 +0x91 fp=0xc0000cb558 sp=0xc0000cb510 pc=0x6730b1
encoding/json.(*sliceEncoder).encode-fm(0xc1d144c8f0, 0x766a60, 0xc13f5d2000, 0x97, 0xc13f5d0100)
        /usr/lib/go-1.11/src/encoding/json/encode.go:755 +0x64 fp=0xc0000cb598 sp=0xc0000cb558 pc=0x67a944
encoding/json.(*encodeState).reflectValue(0xc1d144c8f0, 0x766a60, 0xc13f5d2000, 0x97, 0xc13f5d0100)
        /usr/lib/go-1.11/src/encoding/json/encode.go:333 +0x82 fp=0xc0000cb5d0 sp=0xc0000cb598 pc=0x66f992
encoding/json.interfaceEncoder(0xc1d144c8f0, 0x77e600, 0xc13f57e260, 0x94, 0xc13f570100)
        /usr/lib/go-1.11/src/encoding/json/encode.go:619 +0xab fp=0xc0000cb618 sp=0xc0000cb5d0 pc=0x671beb
encoding/json.(*mapEncoder).encode(0xc00000e0d0, 0xc1d144c8f0, 0x77fc20, 0xc039c7c2a0, 0x15, 0x770100)
        /usr/lib/go-1.11/src/encoding/json/encode.go:692 +0x37b fp=0xc0000cb788 sp=0xc0000cb618 pc=0x67274b
encoding/json.(*mapEncoder).encode-fm(0xc1d144c8f0, 0x77fc20, 0xc039c7c2a0, 0x15, 0xc0000c0100)
        /usr/lib/go-1.11/src/encoding/json/encode.go:708 +0x64 fp=0xc0000cb7c8 sp=0xc0000cb788 pc=0x67a8c4
encoding/json.(*encodeState).reflectValue(0xc1d144c8f0, 0x77fc20, 0xc039c7c2a0, 0x15, 0x790100)
        /usr/lib/go-1.11/src/encoding/json/encode.go:333 +0x82 fp=0xc0000cb800 sp=0xc0000cb7c8 pc=0x66f992
encoding/json.(*encodeState).marshal(0xc1d144c8f0, 0x77fc20, 0xc039c7c2a0, 0x780100, 0x0, 0x0)
        /usr/lib/go-1.11/src/encoding/json/encode.go:305 +0xf4 fp=0xc0000cb848 sp=0xc0000cb800 pc=0x66f444
encoding/json.(*Encoder).Encode(0xc0000cb9d8, 0x77fc20, 0xc039c7c2a0, 0x7fcaf05ae040, 0xc039c7c270)
        /usr/lib/go-1.11/src/encoding/json/stream.go:200 +0x8a fp=0xc0000cb8d8 sp=0xc0000cb848 pc=0x6799fa
github.com/alice-lg/birdwatcher/endpoints.Endpoint.func1(0x7fcaf1dfa190, 0xc039c7c270, 0xc081788600, 0xc081f1e380, 0x1, 0x2)
        /root/go/src/github.com/alice-lg/birdwatcher/endpoints/endpoint.go:98 +0x5fd fp=0xc0000cba98 sp=0xc0000cb8d8 pc=0x7174ed
github.com/alice-lg/birdwatcher/vendor/github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc00016c0c0, 0x7fcaf1dfa190, 0xc039c7c270, 0xc081788600)
        /root/go/src/github.com/alice-lg/birdwatcher/vendor/github.com/julienschmidt/httprouter/router.go:299 +0x6c2 fp=0xc0000cbb78 sp=0xc0000cba98 pc=0x70ff82
github.com/alice-lg/birdwatcher/vendor/github.com/gorilla/handlers.loggingHandler.ServeHTTP(0x852660, 0xc000082178, 0x8525e0, 0xc00016c0c0, 0x855680, 0xc09a848460, 0xc081788600)
        /root/go/src/github.com/alice-lg/birdwatcher/vendor/github.com/gorilla/handlers/handlers.go:69 +0x123 fp=0xc0000cbd00 sp=0xc0000cbb78 pc=0x717e73
github.com/alice-lg/birdwatcher/vendor/github.com/gorilla/handlers.(*loggingHandler).ServeHTTP(0xc00000c060, 0x855680, 0xc09a848460, 0xc081788600)
        <autogenerated>:1 +0x75 fp=0xc0000cbd48 sp=0xc0000cbd00 pc=0x71bea5
net/http.serverHandler.ServeHTTP(0xc00017a000, 0x855680, 0xc09a848460, 0xc081788600)
        /usr/lib/go-1.11/src/net/http/server.go:2741 +0xab fp=0xc0000cbd78 sp=0xc0000cbd48 pc=0x61c03b
net/http.(*conn).serve(0xc00014aa00, 0x855980, 0xc000087280)
        /usr/lib/go-1.11/src/net/http/server.go:1847 +0x646 fp=0xc0000cbfc8 sp=0xc0000cbd78 pc=0x618c96
runtime.goexit()
        /usr/lib/go-1.11/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc0000cbfd0 sp=0xc0000cbfc8 pc=0x458841
created by net/http.(*Server).Serve
        /usr/lib/go-1.11/src/net/http/server.go:2851 +0x2f5

goroutine 1 [IO wait, 5 minutes]:
internal/poll.runtime_pollWait(0x7fcaf1df5f00, 0x72, 0x0)
        /usr/lib/go-1.11/src/runtime/netpoll.go:173 +0x66
internal/poll.(*pollDesc).wait(0xc000180018, 0x72, 0xc000054000, 0x0, 0x0)
        /usr/lib/go-1.11/src/internal/poll/fd_poll_runtime.go:85 +0x9a
internal/poll.(*pollDesc).waitRead(0xc000180018, 0xffffffffffffff00, 0x0, 0x0)
        /usr/lib/go-1.11/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Accept(0xc000180000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/lib/go-1.11/src/internal/poll/fd_unix.go:384 +0x1a0
net.(*netFD).accept(0xc000180000, 0x40cfaf, 0xc00018e000, 0xa0)
        /usr/lib/go-1.11/src/net/fd_unix.go:238 +0x42
net.(*TCPListener).accept(0xc00000e018, 0xc0000c9c58, 0x2a047c33, 0xef4eddf748402bf7)
        /usr/lib/go-1.11/src/net/tcpsock_posix.go:139 +0x2e
net.(*TCPListener).AcceptTCP(0xc00000e018, 0xc0000c9c80, 0x483a96, 0x5d36b44e)
        /usr/lib/go-1.11/src/net/tcpsock.go:247 +0x47
net/http.tcpKeepAliveListener.Accept(0xc00000e018, 0xc0000c9cd0, 0x18, 0xc000000300, 0x61c575)
        /usr/lib/go-1.11/src/net/http/server.go:3232 +0x2f
net/http.(*Server).Serve(0xc00017a000, 0x855840, 0xc00000e018, 0x0, 0x0)
        /usr/lib/go-1.11/src/net/http/server.go:2826 +0x22f
net/http.(*Server).ListenAndServe(0xc00017a000, 0xc00017a000, 0x7aab60)
        /usr/lib/go-1.11/src/net/http/server.go:2764 +0xb6
net/http.ListenAndServe(0xc000144ca0, 0xd, 0x852f80, 0xc00000c060, 0x1, 0xe)
        /usr/lib/go-1.11/src/net/http/server.go:3004 +0x74
main.main()
        /root/go/src/github.com/alice-lg/birdwatcher/birdwatcher.go:206 +0x892

goroutine 19 [chan receive]:
github.com/alice-lg/birdwatcher/bird.InstallRateLimitReset.func1()
        /root/go/src/github.com/alice-lg/birdwatcher/bird/bird.go:141 +0xa2
created by github.com/alice-lg/birdwatcher/bird.InstallRateLimitReset
        /root/go/src/github.com/alice-lg/birdwatcher/bird/bird.go:138 +0x35

goroutine 20 [sleep, 3 minutes]:
time.Sleep(0x45d964b800)
        /usr/lib/go-1.11/src/runtime/time.go:105 +0x14f
main.Housekeeping(0x5, 0xc00013e001, 0x1)
        /root/go/src/github.com/alice-lg/birdwatcher/housekeeping.go:21 +0x57
created by main.main
        /root/go/src/github.com/alice-lg/birdwatcher/birdwatcher.go:198 +0x62b

goroutine 48 [IO wait, 4 minutes]:
internal/poll.runtime_pollWait(0x7fcaf1df5e30, 0x72, 0xc000030658)
        /usr/lib/go-1.11/src/runtime/netpoll.go:173 +0x66
internal/poll.(*pollDesc).wait(0xc000109718, 0x72, 0xffffffffffffff00, 0x853520, 0xaca570)
        /usr/lib/go-1.11/src/internal/poll/fd_poll_runtime.go:85 +0x9a
internal/poll.(*pollDesc).waitRead(0xc000109718, 0xc00016c100, 0x1, 0x1)
        /usr/lib/go-1.11/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc000109700, 0xc00016c1f1, 0x1, 0x1, 0x0, 0x0, 0x0)
        /usr/lib/go-1.11/src/internal/poll/fd_unix.go:169 +0x179
net.(*netFD).Read(0xc000109700, 0xc00016c1f1, 0x1, 0x1, 0xc000087318, 0xc000030768, 0x46b6d5)
        /usr/lib/go-1.11/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc000082188, 0xc00016c1f1, 0x1, 0x1, 0x0, 0x0, 0x0)
        /usr/lib/go-1.11/src/net/net.go:177 +0x68
net/http.(*connReader).backgroundRead(0xc00016c1e0)
        /usr/lib/go-1.11/src/net/http/server.go:676 +0x5a
created by net/http.(*connReader).startBackgroundRead
        /usr/lib/go-1.11/src/net/http/server.go:672 +0xd2
```

**Comment by maximiliandallmair** [comment]
seems only happens with v4 full table
please fix

**Comment by maximiliandallmair** [comment]
help?

**Comment by stv0g** [comment]
Happens to me as well when fetching an IPv4 full table.

Possilbly the API should provide some support for pagination or better memory handling / streaming...

**Comment by stv0g** [comment]
You can verify this by checking the kernel log if the OOM killed birdwatcher.

Lets close this issue..
